# Day of the week
MON = "monday"
TUE = "tuesday"
WED = "wednesday"
THU = "thursday"
FRI = "friday"
SAT = "saturday"
SUN = "sunday"

DAYS = [MON, TUE, WED, THU, FRI, SAT, SUN]

TRAINING_DAY = [WED]
WEEKEND = [SAT, SUN]
OTHER_DAY = [MON, TUE, THU, FRI]

TRAINING_DAY_SCORE = 3
WEEKEND_SCORE = 2
OTHER_DAY_SCORE = 1

SCORE_OF_DAY = {}

for day in TRAINING_DAY:
    SCORE_OF_DAY[day] = TRAINING_DAY_SCORE
for day in WEEKEND:
    SCORE_OF_DAY[day] = WEEKEND_SCORE
for day in OTHER_DAY:
    SCORE_OF_DAY[day] = OTHER_DAY_SCORE

# BONUS SCORE
TRAINING_DAY_BONUS_CONDITION = 10
TRAINING_DAY_BONUS_SCORE = 10
WEEKEND_BONUS_CONDITION = 10
WEEKEND_BONUS_SCORE = 10

# GRADE
GOLD = "GOLD"
SILVER = "SILVER"
NORMAL = "NORMAL"

GRADE_CUTLINE = {
    GOLD: 50,
    SILVER: 30,
    NORMAL: 0
}